package:
  name: cyclebars
  version: 0

source:
  git_rev: 
  git_url: https://github.com/klavere/cyclebars

requirements:
  build:
    - python 3.9.5

  run:
    - python 3.9.5
    - numpy 1.21.2
    - pandas 1.3.3
    - matplotlib 3.4.2

test:
  imports:
    -

about:
  home: https://github.com/klavere/cyclebars
  
